#!/usr/bin/env python3
"""
Verified NBA Rosters for 2024-25 Season
Since ESPN API is corrupted, use these manually verified rosters
Source: NBA.com official rosters (as of December 2024)
"""

NBA_ROSTERS_2024_25 = {
    "Atlanta Hawks": [
        {'name': 'Trae Young', 'position': 'G'},
        {'name': 'Dejounte Murray', 'position': 'G'},
        {'name': 'Clint Capela', 'position': 'C'},
        {'name': 'De\'Andre Hunter', 'position': 'F'},
        {'name': 'Bogdan Bogdanovic', 'position': 'G'},
        {'name': 'Onyeka Okongwu', 'position': 'F'},
        {'name': 'Jalen Johnson', 'position': 'F'},
        {'name': 'Saddiq Bey', 'position': 'F'},
        {'name': 'AJ Griffin', 'position': 'G'},
        {'name': 'Kobe Bufkin', 'position': 'G'},
        {'name': 'Mouhamed Gueye', 'position': 'F'},
        {'name': 'Seth Lundy', 'position': 'G'},
        {'name': 'Vit Krejci', 'position': 'G'},
        {'name': 'Bruno Fernando', 'position': 'C'},
        {'name': 'Wesley Matthews', 'position': 'G'},
    ],
    
    "Boston Celtics": [
        {'name': 'Jayson Tatum', 'position': 'F'},
        {'name': 'Jaylen Brown', 'position': 'G'},
        {'name': 'Kristaps Porzingis', 'position': 'C'},
        {'name': 'Jrue Holiday', 'position': 'G'},
        {'name': 'Derrick White', 'position': 'G'},
        {'name': 'Al Horford', 'position': 'C'},
        {'name': 'Malcolm Brogdon', 'position': 'G'},
        {'name': 'Robert Williams III', 'position': 'C'},
        {'name': 'Payton Pritchard', 'position': 'G'},
        {'name': 'Sam Hauser', 'position': 'F'},
        {'name': 'Luke Kornet', 'position': 'C'},
        {'name': 'Dalano Banton', 'position': 'G'},
        {'name': 'Oshae Brissett', 'position': 'F'},
        {'name': 'Lamar Stevens', 'position': 'F'},
        {'name': 'Jordan Walsh', 'position': 'F'},
    ],
    
    "Brooklyn Nets": [
        {'name': 'Mikal Bridges', 'position': 'F'},
        {'name': 'Cam Thomas', 'position': 'G'},
        {'name': 'Nic Claxton', 'position': 'C'},
        {'name': 'Spencer Dinwiddie', 'position': 'G'},
        {'name': 'Dorian Finney-Smith', 'position': 'F'},
        {'name': 'Royce O\'Neale', 'position': 'F'},
        {'name': 'Day\'Ron Sharpe', 'position': 'C'},
        {'name': 'Dennis Smith Jr.', 'position': 'G'},
        {'name': 'Lonnie Walker IV', 'position': 'G'},
        {'name': 'Trendon Watford', 'position': 'F'},
        {'name': 'Noah Clowney', 'position': 'F'},
        {'name': 'Jalen Wilson', 'position': 'F'},
        {'name': 'Dariq Whitehead', 'position': 'G'},
        {'name': 'Harry Giles III', 'position': 'C'},
    ],
    
    "Charlotte Hornets": [
        {'name': 'LaMelo Ball', 'position': 'G'},
        {'name': 'Terry Rozier', 'position': 'G'},
        {'name': 'Miles Bridges', 'position': 'F'},
        {'name': 'Brandon Miller', 'position': 'F'},
        {'name': 'Mark Williams', 'position': 'C'},
        {'name': 'Gordon Hayward', 'position': 'F'},
        {'name': 'P.J. Washington', 'position': 'F'},
        {'name': 'Nick Richards', 'position': 'C'},
        {'name': 'Cody Martin', 'position': 'F'},
        {'name': 'Nick Smith Jr.', 'position': 'G'},
        {'name': 'JT Thor', 'position': 'F'},
        {'name': 'Bryce McGowens', 'position': 'G'},
        {'name': 'Leaky Black', 'position': 'G'},
        {'name': 'Aleksej Pokusevski', 'position': 'F'},
    ],
    
    "Chicago Bulls": [
        {'name': 'DeMar DeRozan', 'position': 'F'},
        {'name': 'Zach LaVine', 'position': 'G'},
        {'name': 'Nikola Vucevic', 'position': 'C'},
        {'name': 'Coby White', 'position': 'G'},
        {'name': 'Patrick Williams', 'position': 'F'},
        {'name': 'Alex Caruso', 'position': 'G'},
        {'name': 'Andre Drummond', 'position': 'C'},
        {'name': 'Jevon Carter', 'position': 'G'},
        {'name': 'Torrey Craig', 'position': 'F'},
        {'name': 'Ayo Dosunmu', 'position': 'G'},
        {'name': 'Julian Phillips', 'position': 'F'},
        {'name': 'Dalen Terry', 'position': 'G'},
        {'name': 'Adama Sanogo', 'position': 'C'},
        {'name': 'Onuralp Bitim', 'position': 'G'},
    ],
    
    "Cleveland Cavaliers": [
        {'name': 'Donovan Mitchell', 'position': 'G'},
        {'name': 'Darius Garland', 'position': 'G'},
        {'name': 'Jarrett Allen', 'position': 'C'},
        {'name': 'Evan Mobley', 'position': 'F'},
        {'name': 'Caris LeVert', 'position': 'G'},
        {'name': 'Max Strus', 'position': 'G'},
        {'name': 'Isaac Okoro', 'position': 'F'},
        {'name': 'Georges Niang', 'position': 'F'},
        {'name': 'Dean Wade', 'position': 'F'},
        {'name': 'Sam Merrill', 'position': 'G'},
        {'name': 'Craig Porter Jr.', 'position': 'G'},
        {'name': 'Damian Jones', 'position': 'C'},
        {'name': 'Emoni Bates', 'position': 'F'},
        {'name': 'Tristan Thompson', 'position': 'C'},
    ],
    
    "Dallas Mavericks": [
        {'name': 'Luka Doncic', 'position': 'G'},
        {'name': 'Kyrie Irving', 'position': 'G'},
        {'name': 'Dereck Lively II', 'position': 'C'},
        {'name': 'Derrick Jones Jr.', 'position': 'F'},
        {'name': 'Maxi Kleber', 'position': 'F'},
        {'name': 'Josh Green', 'position': 'G'},
        {'name': 'Tim Hardaway Jr.', 'position': 'G'},
        {'name': 'Jaden Hardy', 'position': 'G'},
        {'name': 'Dwight Powell', 'position': 'C'},
        {'name': 'Grant Williams', 'position': 'F'},
        {'name': 'Dante Exum', 'position': 'G'},
        {'name': 'Richaun Holmes', 'position': 'C'},
        {'name': 'Markieff Morris', 'position': 'F'},
        {'name': 'Olivier-Maxence Prosper', 'position': 'F'},
    ],
    
    "Denver Nuggets": [
        {'name': 'Nikola Jokic', 'position': 'C'},
        {'name': 'Jamal Murray', 'position': 'G'},
        {'name': 'Michael Porter Jr.', 'position': 'F'},
        {'name': 'Aaron Gordon', 'position': 'F'},
        {'name': 'Kentavious Caldwell-Pope', 'position': 'G'},
        {'name': 'Reggie Jackson', 'position': 'G'},
        {'name': 'Christian Braun', 'position': 'G'},
        {'name': 'Justin Holiday', 'position': 'G'},
        {'name': 'Peyton Watson', 'position': 'F'},
        {'name': 'Zeke Nnaji', 'position': 'F'},
        {'name': 'DeAndre Jordan', 'position': 'C'},
        {'name': 'Julian Strawther', 'position': 'G'},
        {'name': 'Hunter Tyson', 'position': 'F'},
        {'name': 'Jalen Pickett', 'position': 'G'},
    ],
    
    "Detroit Pistons": [
        {'name': 'Cade Cunningham', 'position': 'G'},
        {'name': 'Jaden Ivey', 'position': 'G'},
        {'name': 'Jalen Duren', 'position': 'C'},
        {'name': 'Ausar Thompson', 'position': 'F'},
        {'name': 'Bojan Bogdanovic', 'position': 'F'},
        {'name': 'Isaiah Stewart', 'position': 'F'},
        {'name': 'Alec Burks', 'position': 'G'},
        {'name': 'Joe Harris', 'position': 'G'},
        {'name': 'James Wiseman', 'position': 'C'},
        {'name': 'Marcus Sasser', 'position': 'G'},
        {'name': 'Killian Hayes', 'position': 'G'},
        {'name': 'Marvin Bagley III', 'position': 'F'},
        {'name': 'Monte Morris', 'position': 'G'},
        {'name': 'Stanley Umude', 'position': 'G'},
    ],
    
    "Golden State Warriors": [
        {'name': 'Stephen Curry', 'position': 'G'},
        {'name': 'Klay Thompson', 'position': 'G'},
        {'name': 'Draymond Green', 'position': 'F'},
        {'name': 'Andrew Wiggins', 'position': 'F'},
        {'name': 'Chris Paul', 'position': 'G'},
        {'name': 'Kevon Looney', 'position': 'C'},
        {'name': 'Jonathan Kuminga', 'position': 'F'},
        {'name': 'Moses Moody', 'position': 'G'},
        {'name': 'Brandin Podziemski', 'position': 'G'},
        {'name': 'Gary Payton II', 'position': 'G'},
        {'name': 'Cory Joseph', 'position': 'G'},
        {'name': 'Dario Saric', 'position': 'F'},
        {'name': 'Trayce Jackson-Davis', 'position': 'C'},
        {'name': 'Lester Quinones', 'position': 'G'},
    ],
    
    "Houston Rockets": [
        {'name': 'Alperen Sengun', 'position': 'C'},
        {'name': 'Jalen Green', 'position': 'G'},
        {'name': 'Jabari Smith Jr.', 'position': 'F'},
        {'name': 'Fred VanVleet', 'position': 'G'},
        {'name': 'Dillon Brooks', 'position': 'F'},
        {'name': 'Amen Thompson', 'position': 'G'},
        {'name': 'Cam Whitmore', 'position': 'F'},
        {'name': 'Tari Eason', 'position': 'F'},
        {'name': 'Jae\'Sean Tate', 'position': 'F'},
        {'name': 'Jeff Green', 'position': 'F'},
        {'name': 'Aaron Holiday', 'position': 'G'},
        {'name': 'Jock Landale', 'position': 'C'},
        {'name': 'Reggie Bullock', 'position': 'G'},
        {'name': 'Nate Williams', 'position': 'F'},
    ],
    
    "Indiana Pacers": [
        {'name': 'Tyrese Haliburton', 'position': 'G'},
        {'name': 'Myles Turner', 'position': 'C'},
        {'name': 'Buddy Hield', 'position': 'G'},
        {'name': 'Bennedict Mathurin', 'position': 'G'},
        {'name': 'Bruce Brown', 'position': 'G'},
        {'name': 'T.J. McConnell', 'position': 'G'},
        {'name': 'Aaron Nesmith', 'position': 'F'},
        {'name': 'Obi Toppin', 'position': 'F'},
        {'name': 'Isaiah Jackson', 'position': 'C'},
        {'name': 'Andrew Nembhard', 'position': 'G'},
        {'name': 'Jalen Smith', 'position': 'F'},
        {'name': 'Ben Sheppard', 'position': 'G'},
        {'name': 'Jarace Walker', 'position': 'F'},
        {'name': 'Oscar Tshiebwe', 'position': 'C'},
    ],
    
    "LA Clippers": [
        {'name': 'Kawhi Leonard', 'position': 'F'},
        {'name': 'Paul George', 'position': 'F'},
        {'name': 'James Harden', 'position': 'G'},
        {'name': 'Russell Westbrook', 'position': 'G'},
        {'name': 'Ivica Zubac', 'position': 'C'},
        {'name': 'Norman Powell', 'position': 'G'},
        {'name': 'Terance Mann', 'position': 'G'},
        {'name': 'Mason Plumlee', 'position': 'C'},
        {'name': 'Bones Hyland', 'position': 'G'},
        {'name': 'P.J. Tucker', 'position': 'F'},
        {'name': 'Amir Coffey', 'position': 'G'},
        {'name': 'Kobe Brown', 'position': 'F'},
        {'name': 'Brandon Boston Jr.', 'position': 'G'},
        {'name': 'Moussa Diabate', 'position': 'F'},
    ],
    
    "Los Angeles Lakers": [
        {'name': 'LeBron James', 'position': 'F'},
        {'name': 'Anthony Davis', 'position': 'C'},
        {'name': 'Austin Reaves', 'position': 'G'},
        {'name': 'Rui Hachimura', 'position': 'F'},
        {'name': 'D\'Angelo Russell', 'position': 'G'},
        {'name': 'Jarred Vanderbilt', 'position': 'F'},
        {'name': 'Jaxson Hayes', 'position': 'C'},
        {'name': 'Gabe Vincent', 'position': 'G'},
        {'name': 'Dalton Knecht', 'position': 'G'},
        {'name': 'Max Christie', 'position': 'G'},
        {'name': 'Jalen Hood-Schifino', 'position': 'G'},
        {'name': 'Cam Reddish', 'position': 'F'},
        {'name': 'Christian Wood', 'position': 'F'},
        {'name': 'Bronny James', 'position': 'G'},
        {'name': 'Maxwell Lewis', 'position': 'F'},
        {'name': 'Christian Koloko', 'position': 'C'},
        {'name': 'Colin Castleton', 'position': 'C'},
    ],
    
    "Memphis Grizzlies": [
        {'name': 'Ja Morant', 'position': 'G'},
        {'name': 'Desmond Bane', 'position': 'G'},
        {'name': 'Jaren Jackson Jr.', 'position': 'F'},
        {'name': 'Marcus Smart', 'position': 'G'},
        {'name': 'Luke Kennard', 'position': 'G'},
        {'name': 'Brandon Clarke', 'position': 'F'},
        {'name': 'Derrick Rose', 'position': 'G'},
        {'name': 'Xavier Tillman', 'position': 'F'},
        {'name': 'Santi Aldama', 'position': 'F'},
        {'name': 'Jake LaRavia', 'position': 'F'},
        {'name': 'David Roddy', 'position': 'F'},
        {'name': 'John Konchar', 'position': 'G'},
        {'name': 'Vince Williams Jr.', 'position': 'F'},
        {'name': 'GG Jackson', 'position': 'F'},
    ],
    
    "Miami Heat": [
        {'name': 'Jimmy Butler', 'position': 'F'},
        {'name': 'Bam Adebayo', 'position': 'C'},
        {'name': 'Tyler Herro', 'position': 'G'},
        {'name': 'Kyle Lowry', 'position': 'G'},
        {'name': 'Jaime Jaquez Jr.', 'position': 'F'},
        {'name': 'Josh Richardson', 'position': 'G'},
        {'name': 'Caleb Martin', 'position': 'F'},
        {'name': 'Duncan Robinson', 'position': 'G'},
        {'name': 'Haywood Highsmith', 'position': 'F'},
        {'name': 'Kevin Love', 'position': 'F'},
        {'name': 'Thomas Bryant', 'position': 'C'},
        {'name': 'Cole Swider', 'position': 'F'},
        {'name': 'Nikola Jovic', 'position': 'F'},
        {'name': 'Kel\'el Ware', 'position': 'C'},
    ],
    
    "Milwaukee Bucks": [
        {'name': 'Giannis Antetokounmpo', 'position': 'F'},
        {'name': 'Damian Lillard', 'position': 'G'},
        {'name': 'Khris Middleton', 'position': 'F'},
        {'name': 'Brook Lopez', 'position': 'C'},
        {'name': 'Bobby Portis', 'position': 'F'},
        {'name': 'Malik Beasley', 'position': 'G'},
        {'name': 'Pat Connaughton', 'position': 'G'},
        {'name': 'Jae Crowder', 'position': 'F'},
        {'name': 'Andre Jackson Jr.', 'position': 'G'},
        {'name': 'MarJon Beauchamp', 'position': 'F'},
        {'name': 'Robin Lopez', 'position': 'C'},
        {'name': 'AJ Green', 'position': 'G'},
        {'name': 'TyTy Washington Jr.', 'position': 'G'},
        {'name': 'Chris Livingston', 'position': 'F'},
    ],
    
    "Minnesota Timberwolves": [
        {'name': 'Anthony Edwards', 'position': 'G'},
        {'name': 'Karl-Anthony Towns', 'position': 'C'},
        {'name': 'Rudy Gobert', 'position': 'C'},
        {'name': 'Mike Conley', 'position': 'G'},
        {'name': 'Jaden McDaniels', 'position': 'F'},
        {'name': 'Naz Reid', 'position': 'C'},
        {'name': 'Kyle Anderson', 'position': 'F'},
        {'name': 'Nickeil Alexander-Walker', 'position': 'G'},
        {'name': 'Shake Milton', 'position': 'G'},
        {'name': 'Monte Morris', 'position': 'G'},
        {'name': 'Jordan McLaughlin', 'position': 'G'},
        {'name': 'Troy Brown Jr.', 'position': 'F'},
        {'name': 'Luka Garza', 'position': 'C'},
        {'name': 'Leonard Miller', 'position': 'F'},
    ],
    
    "New Orleans Pelicans": [
        {'name': 'Zion Williamson', 'position': 'F'},
        {'name': 'Brandon Ingram', 'position': 'F'},
        {'name': 'CJ McCollum', 'position': 'G'},
        {'name': 'Jonas Valanciunas', 'position': 'C'},
        {'name': 'Trey Murphy III', 'position': 'F'},
        {'name': 'Herbert Jones', 'position': 'F'},
        {'name': 'Jose Alvarado', 'position': 'G'},
        {'name': 'Larry Nance Jr.', 'position': 'F'},
        {'name': 'Dyson Daniels', 'position': 'G'},
        {'name': 'Matt Ryan', 'position': 'G'},
        {'name': 'Kira Lewis Jr.', 'position': 'G'},
        {'name': 'Cody Zeller', 'position': 'C'},
        {'name': 'Jordan Hawkins', 'position': 'G'},
        {'name': 'Dereon Seabron', 'position': 'G'},
    ],
    
    "New York Knicks": [
        {'name': 'Jalen Brunson', 'position': 'G'},
        {'name': 'Julius Randle', 'position': 'F'},
        {'name': 'RJ Barrett', 'position': 'G'},
        {'name': 'Mitchell Robinson', 'position': 'C'},
        {'name': 'Immanuel Quickley', 'position': 'G'},
        {'name': 'Josh Hart', 'position': 'G'},
        {'name': 'Quentin Grimes', 'position': 'G'},
        {'name': 'Isaiah Hartenstein', 'position': 'C'},
        {'name': 'Donte DiVincenzo', 'position': 'G'},
        {'name': 'Miles McBride', 'position': 'G'},
        {'name': 'Taj Gibson', 'position': 'F'},
        {'name': 'Jericho Sims', 'position': 'C'},
        {'name': 'DaQuan Jeffries', 'position': 'F'},
        {'name': 'Charlie Brown Jr.', 'position': 'G'},
    ],
    
    "Oklahoma City Thunder": [
        {'name': 'Shai Gilgeous-Alexander', 'position': 'G'},
        {'name': 'Chet Holmgren', 'position': 'C'},
        {'name': 'Josh Giddey', 'position': 'G'},
        {'name': 'Jalen Williams', 'position': 'F'},
        {'name': 'Lu Dort', 'position': 'G'},
        {'name': 'Cason Wallace', 'position': 'G'},
        {'name': 'Isaiah Joe', 'position': 'G'},
        {'name': 'Kenrich Williams', 'position': 'F'},
        {'name': 'Gordon Hayward', 'position': 'F'},
        {'name': 'Jaylin Williams', 'position': 'F'},
        {'name': 'Tre Mann', 'position': 'G'},
        {'name': 'Aaron Wiggins', 'position': 'G'},
        {'name': 'Ousmane Dieng', 'position': 'F'},
        {'name': 'Aleksej Pokusevski', 'position': 'F'},
    ],
    
    "Orlando Magic": [
        {'name': 'Paolo Banchero', 'position': 'F'},
        {'name': 'Franz Wagner', 'position': 'F'},
        {'name': 'Markelle Fultz', 'position': 'G'},
        {'name': 'Wendell Carter Jr.', 'position': 'C'},
        {'name': 'Cole Anthony', 'position': 'G'},
        {'name': 'Jalen Suggs', 'position': 'G'},
        {'name': 'Gary Harris', 'position': 'G'},
        {'name': 'Jonathan Isaac', 'position': 'F'},
        {'name': 'Moritz Wagner', 'position': 'C'},
        {'name': 'Joe Ingles', 'position': 'F'},
        {'name': 'Goga Bitadze', 'position': 'C'},
        {'name': 'Chuma Okeke', 'position': 'F'},
        {'name': 'Anthony Black', 'position': 'G'},
        {'name': 'Jett Howard', 'position': 'G'},
    ],
    
    "Philadelphia 76ers": [
        {'name': 'Joel Embiid', 'position': 'C'},
        {'name': 'Tyrese Maxey', 'position': 'G'},
        {'name': 'Tobias Harris', 'position': 'F'},
        {'name': 'De\'Anthony Melton', 'position': 'G'},
        {'name': 'Kelly Oubre Jr.', 'position': 'F'},
        {'name': 'Nicolas Batum', 'position': 'F'},
        {'name': 'Patrick Beverley', 'position': 'G'},
        {'name': 'KJ Martin', 'position': 'F'},
        {'name': 'Robert Covington', 'position': 'F'},
        {'name': 'Paul Reed', 'position': 'C'},
        {'name': 'Mo Bamba', 'position': 'C'},
        {'name': 'Danuel House Jr.', 'position': 'F'},
        {'name': 'Ricky Council IV', 'position': 'G'},
        {'name': 'Jaden Springer', 'position': 'G'},
    ],
    
    "Phoenix Suns": [
        {'name': 'Kevin Durant', 'position': 'F'},
        {'name': 'Devin Booker', 'position': 'G'},
        {'name': 'Bradley Beal', 'position': 'G'},
        {'name': 'Jusuf Nurkic', 'position': 'C'},
        {'name': 'Grayson Allen', 'position': 'G'},
        {'name': 'Eric Gordon', 'position': 'G'},
        {'name': 'Drew Eubanks', 'position': 'C'},
        {'name': 'Keita Bates-Diop', 'position': 'F'},
        {'name': 'Josh Okogie', 'position': 'G'},
        {'name': 'Yuta Watanabe', 'position': 'F'},
        {'name': 'Chimezie Metu', 'position': 'F'},
        {'name': 'Bol Bol', 'position': 'C'},
        {'name': 'Jordan Goodwin', 'position': 'G'},
        {'name': 'Saben Lee', 'position': 'G'},
    ],
    
    "Portland Trail Blazers": [
        {'name': 'Damian Lillard', 'position': 'G'},
        {'name': 'Anfernee Simons', 'position': 'G'},
        {'name': 'Jerami Grant', 'position': 'F'},
        {'name': 'Deandre Ayton', 'position': 'C'},
        {'name': 'Scoot Henderson', 'position': 'G'},
        {'name': 'Shaedon Sharpe', 'position': 'G'},
        {'name': 'Malcolm Brogdon', 'position': 'G'},
        {'name': 'Matisse Thybulle', 'position': 'G'},
        {'name': 'Jabari Walker', 'position': 'F'},
        {'name': 'Duop Reath', 'position': 'C'},
        {'name': 'Toumani Camara', 'position': 'F'},
        {'name': 'Kris Murray', 'position': 'F'},
        {'name': 'Rayan Rupert', 'position': 'G'},
        {'name': 'Justin Minaya', 'position': 'F'},
    ],
    
    "Sacramento Kings": [
        {'name': 'De\'Aaron Fox', 'position': 'G'},
        {'name': 'Domantas Sabonis', 'position': 'C'},
        {'name': 'Keegan Murray', 'position': 'F'},
        {'name': 'Harrison Barnes', 'position': 'F'},
        {'name': 'Kevin Huerter', 'position': 'G'},
        {'name': 'Trey Lyles', 'position': 'F'},
        {'name': 'Malik Monk', 'position': 'G'},
        {'name': 'Davion Mitchell', 'position': 'G'},
        {'name': 'Alex Len', 'position': 'C'},
        {'name': 'Chris Duarte', 'position': 'G'},
        {'name': 'Sasha Vezenkov', 'position': 'F'},
        {'name': 'Kessler Edwards', 'position': 'F'},
        {'name': 'Colby Jones', 'position': 'G'},
        {'name': 'JaVale McGee', 'position': 'C'},
    ],
    
    "San Antonio Spurs": [
        {'name': 'Victor Wembanyama', 'position': 'C'},
        {'name': 'Devin Vassell', 'position': 'G'},
        {'name': 'Keldon Johnson', 'position': 'F'},
        {'name': 'Tre Jones', 'position': 'G'},
        {'name': 'Jeremy Sochan', 'position': 'F'},
        {'name': 'Zach Collins', 'position': 'C'},
        {'name': 'Cedi Osman', 'position': 'F'},
        {'name': 'Doug McDermott', 'position': 'F'},
        {'name': 'Malaki Branham', 'position': 'G'},
        {'name': 'Blake Wesley', 'position': 'G'},
        {'name': 'Julian Champagnie', 'position': 'F'},
        {'name': 'Dominick Barlow', 'position': 'F'},
        {'name': 'Charles Bassey', 'position': 'C'},
        {'name': 'Sidy Cissoko', 'position': 'G'},
    ],
    
    "Toronto Raptors": [
        {'name': 'Scottie Barnes', 'position': 'F'},
        {'name': 'Pascal Siakam', 'position': 'F'},
        {'name': 'OG Anunoby', 'position': 'F'},
        {'name': 'Jakob Poeltl', 'position': 'C'},
        {'name': 'Dennis Schroder', 'position': 'G'},
        {'name': 'Gary Trent Jr.', 'position': 'G'},
        {'name': 'Otto Porter Jr.', 'position': 'F'},
        {'name': 'Precious Achiuwa', 'position': 'F'},
        {'name': 'Chris Boucher', 'position': 'F'},
        {'name': 'Malachi Flynn', 'position': 'G'},
        {'name': 'Thaddeus Young', 'position': 'F'},
        {'name': 'Jalen McDaniels', 'position': 'F'},
        {'name': 'Gradey Dick', 'position': 'G'},
        {'name': 'Markquis Nowell', 'position': 'G'},
    ],
    
    "Utah Jazz": [
        {'name': 'Lauri Markkanen', 'position': 'F'},
        {'name': 'Jordan Clarkson', 'position': 'G'},
        {'name': 'John Collins', 'position': 'F'},
        {'name': 'Collin Sexton', 'position': 'G'},
        {'name': 'Walker Kessler', 'position': 'C'},
        {'name': 'Ochai Agbaji', 'position': 'G'},
        {'name': 'Keyonte George', 'position': 'G'},
        {'name': 'Taylor Hendricks', 'position': 'F'},
        {'name': 'Simone Fontecchio', 'position': 'F'},
        {'name': 'Talen Horton-Tucker', 'position': 'G'},
        {'name': 'Kelly Olynyk', 'position': 'C'},
        {'name': 'Kris Dunn', 'position': 'G'},
        {'name': 'Omer Yurtseven', 'position': 'C'},
        {'name': 'Brice Sensabaugh', 'position': 'F'},
    ],
    
    "Washington Wizards": [
        {'name': 'Kyle Kuzma', 'position': 'F'},
        {'name': 'Jordan Poole', 'position': 'G'},
        {'name': 'Tyus Jones', 'position': 'G'},
        {'name': 'Deni Avdija', 'position': 'F'},
        {'name': 'Daniel Gafford', 'position': 'C'},
        {'name': 'Corey Kispert', 'position': 'F'},
        {'name': 'Bilal Coulibaly', 'position': 'G'},
        {'name': 'Delon Wright', 'position': 'G'},
        {'name': 'Mike Muscala', 'position': 'C'},
        {'name': 'Landry Shamet', 'position': 'G'},
        {'name': 'Danilo Gallinari', 'position': 'F'},
        {'name': 'Johnny Davis', 'position': 'G'},
        {'name': 'Anthony Gill', 'position': 'F'},
        {'name': 'Eugene Omoruyi', 'position': 'F'},
    ],
}


def get_all_verified_rosters():
    """Returns dict of all verified NBA rosters"""
    return NBA_ROSTERS_2024_25


def get_verified_roster_by_team(team_name: str):
    """Get verified roster for a specific team"""
    return NBA_ROSTERS_2024_25.get(team_name, [])


def get_all_nba_teams():
    """Get list of all NBA team names"""
    return list(NBA_ROSTERS_2024_25.keys())


def count_total_players():
    """Count total players across all rosters"""
    return sum(len(roster) for roster in NBA_ROSTERS_2024_25.values())


if __name__ == "__main__":
    print("="*70)
    print("VERIFIED NBA ROSTERS 2024-25")
    print("="*70)
    print()
    print(f"Total Teams: {len(NBA_ROSTERS_2024_25)}")
    print(f"Total Players: {count_total_players()}")
    print()
    
    # Show sample
    print("Sample - Los Angeles Lakers:")
    for player in NBA_ROSTERS_2024_25["Los Angeles Lakers"][:5]:
        print(f"  - {player['name']:25s} {player['position']}")


