"""Scraper template definitions — expanded per sport in build.py."""

from __future__ import annotations

# Per-sport templates: suffix -> definition kwargs (sport filled at build)

CORE_TEMPLATES: list[dict] = [
    {
        "suffix": "espn_roster",
        "display": "ESPN roster",
        "dimension": "identity",
        "source": "espn",
        "source_type": "public_api",
        "description": "Name, school, position, class, jersey, headshot from ESPN.",
        "feature_keys": (
            "player_name",
            "team",
            "position",
            "class_year",
            "jersey_number",
            "height_inches",
            "weight_lbs",
        ),
        "status": "legacy",
        "required_for_scoring": True,
        "sla_days": 7,
        "default_confidence": 0.92,
        "circuit_breaker_source": "espn",
        "priority": 1,
    },
    {
        "suffix": "espn_stats",
        "display": "ESPN stats",
        "dimension": "proof",
        "source": "espn",
        "source_type": "public_api",
        "description": "Season and career statistics, gamelogs.",
        "feature_keys": ("season_stats", "career_stats", "games_played_season", "stats_as_of"),
        "status": "legacy",
        "required_for_scoring": True,
        "sla_days": 3,
        "default_confidence": 0.9,
        "circuit_breaker_source": "espn",
        "priority": 2,
    },
    {
        "suffix": "sports_ref_stats",
        "display": "Sports Reference stats",
        "dimension": "proof",
        "source": "sports_reference",
        "source_type": "scrape",
        "description": "Historical stats backup (PFR / BRef / CFB ref).",
        "feature_keys": ("career_stats", "advanced_stats"),
        "status": "legacy",
        "sla_days": 14,
        "default_confidence": 0.85,
        "circuit_breaker_source": "sports_reference",
        "priority": 4,
    },
    {
        "suffix": "recruiting_247",
        "display": "247Sports recruiting",
        "dimension": "proof",
        "source": "247sports",
        "source_type": "scrape",
        "description": "Stars, national/position/state recruiting ranks.",
        "feature_keys": (
            "recruiting_stars",
            "recruiting_rank_national",
            "recruiting_rank_position",
            "recruiting_state_rank",
        ),
        "status": "legacy",
        "sla_days": 30,
        "default_confidence": 0.75,
        "priority": 4,
    },
    {
        "suffix": "recruiting_rivals",
        "display": "Rivals recruiting",
        "dimension": "proof",
        "source": "rivals",
        "source_type": "scrape",
        "description": "Recruiting profile backup.",
        "feature_keys": ("recruiting_stars", "recruiting_rank_national"),
        "status": "legacy",
        "sla_days": 30,
        "default_confidence": 0.7,
        "priority": 5,
    },
    {
        "suffix": "recruiting_espn",
        "display": "ESPN recruiting",
        "dimension": "proof",
        "source": "espn",
        "source_type": "public_api",
        "description": "ESPN recruiting ranks.",
        "feature_keys": ("recruiting_stars", "recruiting_rank_national"),
        "status": "legacy",
        "sla_days": 30,
        "default_confidence": 0.72,
        "circuit_breaker_source": "espn",
        "priority": 5,
    },
    {
        "suffix": "on3_nil",
        "display": "On3 NIL",
        "dimension": "proximity",
        "source": "on3",
        "source_type": "scrape",
        "description": "NIL valuation, deal announcements, rankings.",
        "feature_keys": ("nil_valuation", "nil_deal_count", "nil_rank_national"),
        "status": "stub",
        "sla_days": 7,
        "default_confidence": 0.95,
        "circuit_breaker_source": "on3",
        "priority": 2,
    },
    {
        "suffix": "opendorse_profile",
        "display": "Opendorse profile",
        "dimension": "proximity",
        "source": "opendorse",
        "source_type": "scrape",
        "description": "Athlete marketplace profile and social metrics.",
        "feature_keys": ("nil_valuation", "marketplace_listing", "social_metrics"),
        "status": "stub",
        "sla_days": 7,
        "default_confidence": 0.9,
        "priority": 3,
    },
    {
        "suffix": "inflcr_social",
        "display": "INFLCR social analytics",
        "dimension": "brand",
        "source": "inflcr",
        "source_type": "licensed",
        "description": "Engagement rates and content activity.",
        "feature_keys": ("engagement_rate", "content_activity_score"),
        "status": "stub",
        "sla_days": 7,
        "default_confidence": 0.85,
        "priority": 4,
    },
    {
        "suffix": "instagram_followers",
        "display": "Instagram followers",
        "dimension": "brand",
        "source": "instagram",
        "source_type": "scrape",
        "description": "Follower count and post count.",
        "feature_keys": ("instagram_followers", "instagram_posts", "instagram_handle"),
        "status": "legacy",
        "required_for_scoring": True,
        "sla_days": 3,
        "default_confidence": 0.8,
        "circuit_breaker_source": "social",
        "priority": 2,
    },
    {
        "suffix": "tiktok_followers",
        "display": "TikTok followers",
        "dimension": "brand",
        "source": "tiktok",
        "source_type": "scrape",
        "description": "TikTok follower count.",
        "feature_keys": ("tiktok_followers", "tiktok_handle"),
        "status": "legacy",
        "sla_days": 3,
        "default_confidence": 0.78,
        "circuit_breaker_source": "social",
        "priority": 3,
    },
    {
        "suffix": "twitter_followers",
        "display": "X/Twitter followers",
        "dimension": "brand",
        "source": "twitter",
        "source_type": "scrape",
        "description": "X follower count.",
        "feature_keys": ("twitter_followers", "twitter_handle"),
        "status": "legacy",
        "sla_days": 3,
        "default_confidence": 0.78,
        "circuit_breaker_source": "social",
        "priority": 3,
    },
    {
        "suffix": "youtube_subscribers",
        "display": "YouTube channel",
        "dimension": "brand",
        "source": "youtube",
        "source_type": "public_api",
        "description": "Subscribers and recent view counts.",
        "feature_keys": ("youtube_subscribers", "youtube_views_30d", "youtube_handle"),
        "status": "planned",
        "sla_days": 7,
        "default_confidence": 0.82,
        "priority": 4,
    },
    {
        "suffix": "transfer_portal",
        "display": "Transfer portal status",
        "dimension": "risk",
        "source": "on3",
        "source_type": "scrape",
        "description": "Portal entry, destination school, timeline.",
        "feature_keys": (
            "in_transfer_portal",
            "portal_entry_date",
            "destination_school",
        ),
        "status": "planned",
        "sla_days": 1,
        "default_confidence": 0.88,
        "circuit_breaker_source": "on3",
        "priority": 1,
    },
]

QUALITY_TEMPLATES: list[dict] = [
    {
        "suffix": "social_handle_discovery",
        "display": "Social handle discovery",
        "dimension": "identity",
        "source": "derived",
        "source_type": "derived",
        "description": "Resolve IG/TikTok/X handles from roster, ESPN, Opendorse, link-in-bio.",
        "feature_keys": (
            "instagram_handle",
            "tiktok_handle",
            "twitter_handle",
            "handle_confidence",
            "handle_source",
        ),
        "status": "planned",
        "required_for_scoring": True,
        "sla_days": 7,
        "default_confidence": 0.85,
        "priority": 1,
    },
    {
        "suffix": "social_engagement_instagram",
        "display": "Instagram engagement",
        "dimension": "brand",
        "source": "instagram",
        "source_type": "scrape",
        "description": "Engagement rate from recent posts.",
        "feature_keys": (
            "instagram_engagement_rate",
            "avg_likes_per_post",
            "posts_30d",
        ),
        "status": "planned",
        "sla_days": 7,
        "default_confidence": 0.8,
        "circuit_breaker_source": "social",
        "priority": 3,
    },
    {
        "suffix": "social_engagement_tiktok",
        "display": "TikTok engagement",
        "dimension": "brand",
        "source": "tiktok",
        "source_type": "scrape",
        "description": "TikTok engagement rate.",
        "feature_keys": ("tiktok_engagement_rate", "tiktok_avg_views"),
        "status": "planned",
        "sla_days": 7,
        "default_confidence": 0.78,
        "circuit_breaker_source": "social",
        "priority": 4,
    },
    {
        "suffix": "ncaa_official_roster",
        "display": "NCAA official roster verifier",
        "dimension": "identity",
        "source": "ncaa",
        "source_type": "official",
        "description": "Cross-check athlete is on official school roster.",
        "feature_keys": (
            "roster_verified_at",
            "is_on_roster",
            "official_jersey",
            "official_position",
        ),
        "status": "planned",
        "required_for_scoring": True,
        "sla_days": 7,
        "default_confidence": 0.95,
        "priority": 1,
    },
    {
        "suffix": "nil_deal_verified",
        "display": "NIL deal verifier",
        "dimension": "proximity",
        "source": "derived",
        "source_type": "derived",
        "description": "Cross-source NIL consensus (On3 + Opendorse + news).",
        "feature_keys": (
            "nil_valuation",
            "nil_valuation_source",
            "nil_deal_count_verified",
            "nil_last_deal_date",
            "nil_confidence",
        ),
        "status": "planned",
        "required_for_scoring": True,
        "sla_days": 7,
        "default_confidence": 0.9,
        "priority": 2,
    },
    {
        "suffix": "google_trends_athlete",
        "display": "Google Trends athlete",
        "dimension": "velocity",
        "source": "google_trends",
        "source_type": "public_api",
        "description": "Search interest vs sport baseline.",
        "feature_keys": ("google_trends_score", "google_trends_momentum_30d"),
        "status": "legacy",
        "sla_days": 7,
        "default_confidence": 0.7,
        "priority": 4,
    },
    {
        "suffix": "wikipedia_pageviews",
        "display": "Wikipedia pageviews",
        "dimension": "brand",
        "source": "wikipedia",
        "source_type": "public_api",
        "description": "7d/30d pageview counts.",
        "feature_keys": ("wikipedia_views_7d", "wikipedia_views_30d"),
        "status": "legacy",
        "sla_days": 7,
        "default_confidence": 0.72,
        "priority": 5,
    },
    {
        "suffix": "media_appearances",
        "display": "Media appearances",
        "dimension": "velocity",
        "source": "derived",
        "source_type": "derived",
        "description": "Podcast/TV/interview appearance counts.",
        "feature_keys": (
            "podcast_appearances_30d",
            "tv_appearances_30d",
            "media_buzz_score",
        ),
        "status": "planned",
        "sla_days": 7,
        "default_confidence": 0.65,
        "priority": 4,
    },
    {
        "suffix": "identity_consensus",
        "display": "Identity consensus",
        "dimension": "identity",
        "source": "derived",
        "source_type": "derived",
        "description": "Reconcile ESPN/NCAA/247 external IDs.",
        "feature_keys": (
            "external_id_espn",
            "external_id_247",
            "identity_match_score",
        ),
        "status": "planned",
        "sla_days": 14,
        "default_confidence": 0.9,
        "priority": 2,
    },
    {
        "suffix": "social_authenticity",
        "display": "Social account authenticity",
        "dimension": "brand",
        "source": "derived",
        "source_type": "derived",
        "description": "Verify official vs fan accounts.",
        "feature_keys": (
            "social_account_verified",
            "social_authenticity_score",
        ),
        "status": "planned",
        "sla_days": 7,
        "default_confidence": 0.85,
        "priority": 3,
    },
    {
        "suffix": "stats_freshness",
        "display": "Stats freshness marker",
        "dimension": "proof",
        "source": "derived",
        "source_type": "derived",
        "description": "When stats were last updated and from which source.",
        "feature_keys": ("stats_as_of", "season_id", "stats_source"),
        "status": "planned",
        "sla_days": 3,
        "default_confidence": 0.95,
        "priority": 2,
    },
    {
        "suffix": "injury_structured",
        "display": "Structured injury feed",
        "dimension": "risk",
        "source": "espn",
        "source_type": "public_api",
        "description": "Current injury status, games missed, risk score.",
        "feature_keys": (
            "current_injury_status",
            "games_missed_season",
            "injury_risk_score",
            "last_injury_date",
        ),
        "status": "planned",
        "sla_days": 1,
        "default_confidence": 0.88,
        "circuit_breaker_source": "espn",
        "priority": 1,
    },
]

ACHIEVEMENT_TEMPLATES: list[dict] = [
    {
        "suffix": "espn_awards",
        "display": "ESPN awards & honors",
        "dimension": "achievements",
        "source": "espn",
        "source_type": "public_api",
        "description": "Conference/national awards, player-of-week, all-conference.",
        "feature_keys": (
            "achievements_json",
            "achievements_count_season",
            "achievements_count_career",
            "conference_honors_count",
            "national_honors_count",
        ),
        "status": "legacy",
        "sla_days": 7,
        "default_confidence": 0.9,
        "circuit_breaker_source": "espn",
        "priority": 3,
    },
    {
        "suffix": "sports_ref_honors",
        "display": "Sports Reference honors",
        "dimension": "achievements",
        "source": "sports_reference",
        "source_type": "scrape",
        "description": "All-Pro, All-Star, awards tables from ref sites.",
        "feature_keys": (
            "achievements_json",
            "all_pro_count",
            "all_star_count",
            "major_awards_json",
        ),
        "status": "legacy",
        "sla_days": 14,
        "default_confidence": 0.88,
        "circuit_breaker_source": "sports_reference",
        "priority": 4,
    },
    {
        "suffix": "all_american",
        "display": "All-American honors",
        "dimension": "achievements",
        "source": "derived",
        "source_type": "derived",
        "description": "AP/Coaches/Walter Camp All-American selections.",
        "feature_keys": (
            "all_american_count",
            "all_american_first_team",
            "achievements_json",
        ),
        "status": "planned",
        "sla_days": 30,
        "default_confidence": 0.92,
        "priority": 4,
    },
    {
        "suffix": "conference_honors",
        "display": "Conference honors",
        "dimension": "achievements",
        "source": "espn",
        "source_type": "public_api",
        "description": "All-conference teams, conference player of year.",
        "feature_keys": (
            "conference_honors_json",
            "conference_honors_count",
            "conference_poty",
        ),
        "status": "planned",
        "sla_days": 14,
        "default_confidence": 0.88,
        "priority": 4,
    },
    {
        "suffix": "championship_results",
        "display": "Championship results",
        "dimension": "achievements",
        "source": "espn",
        "source_type": "public_api",
        "description": "National/conference/tournament titles and appearances.",
        "feature_keys": (
            "national_championships",
            "conference_championships",
            "tournament_final_four",
            "playoff_appearances",
        ),
        "status": "planned",
        "sla_days": 30,
        "default_confidence": 0.9,
        "priority": 5,
    },
    {
        "suffix": "national_awards",
        "display": "National player awards",
        "dimension": "achievements",
        "source": "derived",
        "source_type": "derived",
        "description": "Heisman, Naismith, Golden Spikes, AVCA POY, etc.",
        "feature_keys": (
            "national_awards_json",
            "national_awards_count",
            "heisman_finalist",
            "naismith_candidate",
            "golden_spikes_candidate",
            "avca_player_of_year",
        ),
        "status": "planned",
        "sla_days": 30,
        "default_confidence": 0.93,
        "priority": 4,
    },
]

SPORT_SPECIFIC: list[dict] = [
    {
        "scraper_key": "cfbd_api_stats_cfb",
        "sport": "cfb",
        "display_name": "CollegeFootballData API stats",
        "dimension": "proof",
        "source": "cfbd",
        "source_type": "public_api",
        "description": "Clean CFB stats API alternative to scraping.",
        "feature_keys": ("season_stats", "advanced_stats", "stats_as_of"),
        "status": "planned",
        "sla_days": 3,
        "default_confidence": 0.93,
        "priority": 3,
    },
    {
        "scraper_key": "kenpom_ncaab_mens",
        "sport": "ncaab_mens",
        "display_name": "KenPom analytics",
        "dimension": "proof",
        "source": "kenpom",
        "source_type": "licensed",
        "description": "Advanced MCBB efficiency metrics (licensed).",
        "feature_keys": ("kenpom_rating", "bpm", "usage_rate"),
        "status": "planned",
        "sla_days": 3,
        "default_confidence": 0.95,
        "priority": 3,
    },
    {
        "scraper_key": "her_hoop_stats_ncaab_womens",
        "sport": "ncaab_womens",
        "display_name": "Her Hoop Stats",
        "dimension": "proof",
        "source": "herhoopstats",
        "source_type": "scrape",
        "description": "WCBB advanced stats depth.",
        "feature_keys": ("season_stats", "advanced_stats"),
        "status": "planned",
        "sla_days": 7,
        "default_confidence": 0.85,
        "priority": 4,
    },
    {
        "scraper_key": "perfect_game_recruiting_baseball",
        "sport": "ncaa_baseball",
        "display_name": "Perfect Game recruiting",
        "dimension": "proof",
        "source": "perfect_game",
        "source_type": "scrape",
        "description": "HS rank and draft prospect signal.",
        "feature_keys": ("recruiting_rank_national", "pg_grade", "draft_prospect_rank"),
        "status": "planned",
        "sla_days": 30,
        "default_confidence": 0.88,
        "priority": 3,
    },
    {
        "scraper_key": "d1baseball_rankings_baseball",
        "sport": "ncaa_baseball",
        "display_name": "D1Baseball rankings",
        "dimension": "proof",
        "source": "d1baseball",
        "source_type": "scrape",
        "description": "Team and player national relevance.",
        "feature_keys": ("d1baseball_rank", "team_rank"),
        "status": "planned",
        "sla_days": 7,
        "default_confidence": 0.82,
        "priority": 4,
    },
    {
        "scraper_key": "mlb_draft_pipeline_baseball",
        "sport": "ncaa_baseball",
        "display_name": "MLB draft pipeline",
        "dimension": "proximity",
        "source": "mlb",
        "source_type": "public_api",
        "description": "MLB prospect/draft stock for juniors.",
        "feature_keys": ("mlb_pipeline_rank", "draft_round_projection"),
        "status": "planned",
        "sla_days": 14,
        "default_confidence": 0.9,
        "priority": 4,
    },
    {
        "scraper_key": "avca_poll_volleyball",
        "sport": "ncaa_volleyball",
        "display_name": "AVCA poll rankings",
        "dimension": "proof",
        "source": "avca",
        "source_type": "scrape",
        "description": "National poll rank for teams/players.",
        "feature_keys": ("avca_rank", "avca_poll_points"),
        "status": "planned",
        "sla_days": 7,
        "default_confidence": 0.88,
        "priority": 3,
    },
    {
        "scraper_key": "prepvolleyball_recruiting_volleyball",
        "sport": "ncaa_volleyball",
        "display_name": "PrepVolleyball recruiting",
        "dimension": "proof",
        "source": "prepvolleyball",
        "source_type": "scrape",
        "description": "HS volleyball recruiting ranks.",
        "feature_keys": ("recruiting_stars", "recruiting_rank_national"),
        "status": "planned",
        "sla_days": 30,
        "default_confidence": 0.8,
        "priority": 4,
    },
    {
        "scraper_key": "avca_all_american_volleyball",
        "sport": "ncaa_volleyball",
        "display_name": "AVCA All-American",
        "dimension": "achievements",
        "source": "avca",
        "source_type": "scrape",
        "description": "AVCA All-American team selections.",
        "feature_keys": ("all_american_count", "achievements_json"),
        "status": "planned",
        "sla_days": 30,
        "default_confidence": 0.92,
        "priority": 4,
    },
    {
        "scraper_key": "college_experience_pro",
        "sport": "nfl",
        "display_name": "NFL college career (ESPN)",
        "dimension": "proof",
        "source": "espn",
        "source_type": "public_api",
        "description": "College football career for pro player — predictive modeling.",
        "feature_keys": (
            "college_career_found",
            "college_espn_id",
            "college_stats_json",
            "college_achievements_json",
            "college_team",
            "college_position",
        ),
        "status": "active",
        "required_for_scoring": True,
        "sla_days": 30,
        "default_confidence": 0.9,
        "priority": 2,
    },
    {
        "scraper_key": "college_experience_pro_nba",
        "sport": "nba",
        "display_name": "NBA college career (ESPN)",
        "dimension": "proof",
        "source": "espn",
        "source_type": "public_api",
        "description": "College basketball career for NBA player.",
        "feature_keys": (
            "college_career_found",
            "college_espn_id",
            "college_stats_json",
            "college_achievements_json",
        ),
        "status": "active",
        "required_for_scoring": True,
        "sla_days": 30,
        "default_confidence": 0.9,
        "priority": 2,
    },
    {
        "scraper_key": "spotrac_contract_nfl",
        "sport": "nfl",
        "display_name": "Spotrac NFL contracts",
        "dimension": "proximity",
        "source": "spotrac",
        "source_type": "scrape",
        "description": "Contract value, guarantees, AAV.",
        "feature_keys": (
            "contract_total_usd",
            "contract_guaranteed_usd",
            "contract_aav_usd",
        ),
        "status": "legacy",
        "sla_days": 14,
        "default_confidence": 0.88,
        "priority": 3,
    },
    {
        "scraper_key": "spotrac_contract_nba",
        "sport": "nba",
        "display_name": "Spotrac NBA contracts",
        "dimension": "proximity",
        "source": "spotrac",
        "source_type": "scrape",
        "description": "Contract value, guarantees, AAV.",
        "feature_keys": (
            "contract_total_usd",
            "contract_guaranteed_usd",
            "contract_aav_usd",
        ),
        "status": "legacy",
        "sla_days": 14,
        "default_confidence": 0.88,
        "priority": 3,
    },
    {
        "scraper_key": "forbes_earnings_nba",
        "sport": "nba",
        "display_name": "Forbes NBA earnings",
        "dimension": "proximity",
        "source": "forbes",
        "source_type": "scrape",
        "description": "Endorsement and on-field earnings.",
        "feature_keys": (
            "endorsement_value_usd",
            "total_earnings_usd",
            "forbes_list_rank",
        ),
        "status": "legacy",
        "sla_days": 365,
        "default_confidence": 0.85,
        "priority": 5,
    },
    {
        "scraper_key": "spotrac_contract_wnba",
        "sport": "wnba",
        "display_name": "Spotrac WNBA contracts",
        "dimension": "proximity",
        "source": "spotrac",
        "source_type": "scrape",
        "description": "Contract value, guarantees, AAV.",
        "feature_keys": (
            "contract_total_usd",
            "contract_guaranteed_usd",
            "contract_aav_usd",
        ),
        "status": "legacy",
        "sla_days": 14,
        "default_confidence": 0.88,
        "priority": 3,
    },
    {
        "scraper_key": "forbes_earnings_wnba",
        "sport": "wnba",
        "display_name": "Forbes WNBA earnings",
        "dimension": "proximity",
        "source": "forbes",
        "source_type": "scrape",
        "description": "Endorsement and on-field earnings.",
        "feature_keys": (
            "endorsement_value_usd",
            "total_earnings_usd",
            "forbes_list_rank",
        ),
        "status": "legacy",
        "sla_days": 365,
        "default_confidence": 0.85,
        "priority": 5,
    },
    {
        "scraper_key": "forbes_earnings_nfl",
        "sport": "nfl",
        "display_name": "Forbes NFL earnings",
        "dimension": "proximity",
        "source": "forbes",
        "source_type": "scrape",
        "description": "Endorsement and on-field earnings.",
        "feature_keys": (
            "endorsement_value_usd",
            "total_earnings_usd",
            "forbes_list_rank",
        ),
        "status": "legacy",
        "sla_days": 365,
        "default_confidence": 0.85,
        "priority": 5,
    },
    {
        "scraper_key": "fantasy_adp_nfl",
        "sport": "nfl",
        "display_name": "Fantasy ADP NFL",
        "dimension": "velocity",
        "source": "fantasy",
        "source_type": "scrape",
        "description": "Fantasy average draft position as buzz proxy.",
        "feature_keys": ("fantasy_adp", "fantasy_trend_30d"),
        "status": "planned",
        "sla_days": 7,
        "default_confidence": 0.7,
        "priority": 5,
    },
]

SHARED_SCRAPERS: list[dict] = [
    {
        "scraper_key": "news_rss_on3",
        "sport": "*",
        "display_name": "On3 news RSS",
        "dimension": "velocity",
        "source": "on3",
        "source_type": "public_api",
        "description": "On3 top stories feed.",
        "feature_keys": ("news_count_30d", "news_headlines_json"),
        "status": "active",
        "sla_days": 1,
        "default_confidence": 0.8,
        "priority": 2,
        "metadata": {"repo": "gravity_api", "module": "news_collector.py"},
    },
    {
        "scraper_key": "news_rss_espn_cfb",
        "sport": "cfb",
        "display_name": "ESPN CFB news RSS",
        "dimension": "velocity",
        "source": "espn",
        "source_type": "public_api",
        "description": "ESPN college football RSS.",
        "feature_keys": ("news_count_30d",),
        "status": "active",
        "sla_days": 1,
        "default_confidence": 0.82,
        "priority": 2,
        "metadata": {"repo": "gravity_api", "module": "news_collector.py"},
    },
    {
        "scraper_key": "news_rss_espn_ncaab_mens",
        "sport": "ncaab_mens",
        "display_name": "ESPN MCBB news RSS",
        "dimension": "velocity",
        "source": "espn",
        "source_type": "public_api",
        "description": "ESPN men's college basketball RSS.",
        "feature_keys": ("news_count_30d",),
        "status": "active",
        "sla_days": 1,
        "default_confidence": 0.82,
        "priority": 2,
        "metadata": {"repo": "gravity_api", "module": "news_collector.py"},
    },
    {
        "scraper_key": "news_rss_espn_ncaab_womens",
        "sport": "ncaab_womens",
        "display_name": "ESPN WCBB news RSS",
        "dimension": "velocity",
        "source": "espn",
        "source_type": "public_api",
        "description": "ESPN women's college basketball RSS.",
        "feature_keys": ("news_count_30d",),
        "status": "active",
        "sla_days": 1,
        "default_confidence": 0.82,
        "priority": 2,
        "metadata": {"repo": "gravity_api", "module": "news_collector.py"},
    },
    {
        "scraper_key": "news_rss_espn_baseball",
        "sport": "ncaa_baseball",
        "display_name": "ESPN college baseball RSS",
        "dimension": "velocity",
        "source": "espn",
        "source_type": "public_api",
        "description": "ESPN college baseball news (planned feed URL).",
        "feature_keys": ("news_count_30d",),
        "status": "planned",
        "sla_days": 1,
        "default_confidence": 0.8,
        "priority": 3,
    },
    {
        "scraper_key": "news_rss_espn_volleyball",
        "sport": "ncaa_volleyball",
        "display_name": "ESPN WVB news RSS",
        "dimension": "velocity",
        "source": "espn",
        "source_type": "public_api",
        "description": "ESPN women's volleyball news (planned feed URL).",
        "feature_keys": ("news_count_30d",),
        "status": "planned",
        "sla_days": 1,
        "default_confidence": 0.8,
        "priority": 3,
    },
    {
        "scraper_key": "program_context",
        "sport": "*",
        "display_name": "Program / school context",
        "dimension": "proximity",
        "source": "derived",
        "source_type": "derived",
        "description": "DMA rank, conference media index, collective budget, program social.",
        "feature_keys": (
            "program_gravity_score",
            "school_market_rank",
            "nil_environment_score",
            "conference_media_index",
        ),
        "status": "planned",
        "sla_days": 30,
        "default_confidence": 0.75,
        "priority": 4,
    },
    {
        "scraper_key": "social_growth_delta",
        "sport": "*",
        "display_name": "Social growth delta",
        "dimension": "velocity",
        "source": "derived",
        "source_type": "derived",
        "description": "Follower growth from prior social_snapshots.",
        "feature_keys": (
            "instagram_growth_30d",
            "tiktok_growth_30d",
            "twitter_growth_30d",
        ),
        "status": "legacy",
        "sla_days": 3,
        "default_confidence": 0.85,
        "priority": 3,
        "metadata": {"repo": "gravity", "module": "social_growth_tracker.py"},
    },
    {
        "scraper_key": "perplexity_gap_fill",
        "sport": "*",
        "display_name": "Perplexity gap fill",
        "dimension": "identity",
        "source": "perplexity",
        "source_type": "licensed",
        "description": "Last-resort AI field fill after all sources fail.",
        "feature_keys": ("gap_fill_fields_json",),
        "status": "legacy",
        "sla_days": 999,
        "default_confidence": 0.4,
        "priority": 9,
        "metadata": {"repo": "gravity", "module": "perplexity_fallback.py", "last_resort": True},
    },
]

ACHIEVEMENT_SPORTS = frozenset(
    {
        "cfb",
        "ncaab_mens",
        "ncaab_womens",
        "ncaa_baseball",
        "ncaa_volleyball",
        "nfl",
        "nba",
        "wnba",
    }
)

SPORT_TEMPLATE_GROUPS: dict[str, list[str]] = {
    "cfb": ["core", "quality", "achievements"],
    "ncaab_mens": ["core", "quality", "achievements"],
    "ncaab_womens": ["core", "quality", "achievements"],
    "ncaa_baseball": ["core", "quality", "achievements"],
    "ncaa_volleyball": ["core", "quality", "achievements"],
    "nfl": ["core", "quality", "achievements"],
    "nba": ["core", "quality", "achievements"],
    "wnba": ["core", "quality", "achievements"],
}

TEMPLATE_GROUPS: dict[str, list[dict]] = {
    "core": CORE_TEMPLATES,
    "quality": QUALITY_TEMPLATES,
    "achievements": ACHIEVEMENT_TEMPLATES,
}
