"""Canonical stat keys per sport — scoring keys + extended scrape targets."""

from __future__ import annotations

# Extended stats scraped and stored even when not weighted in proof composites.
EXTENDED_STATS: dict[str, tuple[str, ...]] = {
    "cfb": (
        "pass_attempts",
        "pass_completions",
        "pass_cmp_pct",
        "pass_yards_per_attempt",
        "pass_long",
        "pass_sacks",
        "pass_sack_yards_lost",
        "rush_attempts",
        "rush_long",
        "rec_targets",
        "rec_long",
        "scrimmage_plays",
        "total_tackles",
        "solo_tackles",
        "assist_tackles",
        "passes_defended",
        "forced_fumbles",
        "fumble_recoveries",
        "defensive_td",
        "qb_hurries",
        "fg_attempts",
        "fg_missed",
        "xp_attempts",
        "punt_attempts",
        "punt_yards",
        "kickoff_touchbacks",
        "snaps",
        "snap_pct",
    ),
    "nfl": (
        "pass_attempts",
        "pass_completions",
        "pass_cmp_pct",
        "pass_yards_per_attempt",
        "pass_long",
        "pass_sacks",
        "rush_attempts",
        "rec_targets",
        "total_tackles",
        "solo_tackles",
        "passes_defended",
        "forced_fumbles",
        "epa_per_play",
        "epa_pass",
        "epa_rush",
        "snap_count",
        "snap_pct",
        "fg_attempts",
        "punt_yards",
    ),
    "ncaab_mens": (
        "min",
        "gp",
        "fgm",
        "fga",
        "fg_pct",
        "fg3m",
        "fg3a",
        "ftm",
        "fta",
        "ft_pct",
        "oreb",
        "dreb",
        "pf",
        "eff",
        "per",
        "bpm",
        "usage",
        "ts_pct",
        "efg_pct",
        "ast_to_ratio",
        "double_doubles",
        "triple_doubles",
    ),
    "ncaab_womens": (
        "min",
        "gp",
        "fgm",
        "fga",
        "fg_pct",
        "fg3m",
        "fg3a",
        "ftm",
        "fta",
        "ft_pct",
        "oreb",
        "dreb",
        "pf",
        "eff",
        "per",
        "bpm",
        "usage",
        "ts_pct",
        "double_doubles",
    ),
    "nba": (
        "min",
        "gp",
        "fgm",
        "fga",
        "fg_pct",
        "fg3m",
        "fg3a",
        "ftm",
        "fta",
        "ft_pct",
        "oreb",
        "dreb",
        "pf",
        "per",
        "bpm",
        "usage",
        "ts_pct",
        "efg_pct",
        "ast_to_ratio",
        "double_doubles",
        "triple_doubles",
        "plus_minus",
        "pie",
        "vorp",
        "ws",
        "ws_per_48",
    ),
    "wnba": (
        "min",
        "gp",
        "fgm",
        "fga",
        "fg_pct",
        "fg3m",
        "fg3a",
        "ftm",
        "fta",
        "ft_pct",
        "oreb",
        "dreb",
        "pf",
        "per",
        "bpm",
        "usage",
        "ts_pct",
        "double_doubles",
        "plus_minus",
    ),
    "ncaa_baseball": (
        "g",
        "gs",
        "ab",
        "r",
        "h",
        "hr",
        "rbi",
        "bb",
        "so",
        "hbp",
        "sf",
        "sb",
        "cs",
        "avg",
        "obp",
        "slg",
        "ops",
        "whip",
        "k9",
        "bb9",
        "k_bb",
        "w",
        "l",
        "sv",
        "bs",
        "hld",
        "ip",
        "h_allowed",
        "er",
        "era",
        "fielding_pct",
        "errors",
        "rf_assists",
        "cs_pct",
        "pickoffs",
    ),
    "ncaa_volleyball": (
        "gp",
        "sets_played",
        "kills",
        "kills_per_set",
        "errors",
        "total_attacks",
        "hitting_pct",
        "assists",
        "assists_per_set",
        "aces",
        "service_errors",
        "blocks",
        "blocks_per_set",
        "block_errors",
        "digs",
        "digs_per_set",
        "reception_errors",
        "receive_rating",
        "setting_efficiency",
        "points",
        "points_per_set",
    ),
}


def _scoring_keys_for_sport(sport: str) -> set[str]:
    from gravity_api.feature_engineering.sport_specs import get_sport_spec

    try:
        spec = get_sport_spec(sport)
    except KeyError:
        return set()
    keys: set[str] = set()
    for pg in spec.position_groups:
        for sw in pg.performance_stats:
            keys.add(sw.stat_key)
        keys.update(pg.recruiting_stats)
    return keys


def all_stat_keys_for_sport(sport: str) -> frozenset[str]:
    """Union of proof-weighted keys + extended scrape keys for a sport."""
    keys = _scoring_keys_for_sport(sport)
    keys.update(EXTENDED_STATS.get(sport, ()))
    keys.add("games_played_season")
    keys.add("games_played_career")
    return frozenset(keys)


__all__ = ["EXTENDED_STATS", "all_stat_keys_for_sport"]
